kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
spec:
  replicas: {{ .Values.clusterSize }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
      app.kubernetes.io/part-of: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName }}
        app.kubernetes.io/part-of: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      hostNetwork: true
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodeSelector }}
      tolerations:
        - effect: NoExecute
          key: {{ .Values.nodeSelector }}
          operator: Equal
          value: "true"
      containers:
        - name: {{ .Values.serviceName }}
          image: {{ .Values.appImage }}
          args:
          {{ template "traefik.args" . }}
          ports:
          {{ template "traefik.ports" . }}
          livenessProbe:
          {{ template "traefik.liveness" . }}
          readinessProbe:
          {{ template "traefik.readiness" . }}
